### ISSUE TITLE
Commit messages violate git commit standards

### ISSUE THREAD

**Issue by rumbidzaishem** [RameezFridie/mid-assessment-web#7]
![image](https://github.com/RameezFridie/mid-assessment-web/assets/50237365/40606681-89a4-4a41-aeca-f87aa5201ca7)

![image](https://github.com/RameezFridie/mid-assessment-web/assets/50237365/124c5416-9961-4e27-82e0-35f20194fb6f)

**Comment by RameezFridie** [comment]
I have updated and adapted a more systematic way of commiting
